// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URESERVE_Api.DAL;

#nullable disable

namespace URESERVE_Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250616020451_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Data.Models.Cubiculos", b =>
                {
                    b.Property<int>("CubiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.HasKey("CubiculoId");

                    b.ToTable("Cubiculos");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaCubiculo", b =>
                {
                    b.Property<int>("DetalleReservaCubiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CubiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCubiculo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservacionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleReservaCubiculoId");

                    b.HasIndex("CubiculoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("DetallesReservaCubiculos");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaLaboratorio", b =>
                {
                    b.Property<int>("DetalleReservaLaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdLaboratorio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaboratorioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservacionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleReservaLaboratorioId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("DetallesReservaLaboratorios");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaProyector", b =>
                {
                    b.Property<int>("DetalleReservaProyectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProyector")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservacionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleReservaProyectorId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ProyectorId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("DetallesReservaProyectores");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaRestaurante", b =>
                {
                    b.Property<int>("DetalleReservaRestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRestaurante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleReservaRestauranteId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ReservacionId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("DetallesReservaRestaurantes");
                });

            modelBuilder.Entity("Data.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Data.Models.Laboratorios", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.HasKey("LaboratorioId");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("Data.Models.Proyectores", b =>
                {
                    b.Property<int>("ProyectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.HasKey("ProyectorId");

                    b.ToTable("Proyectores");
                });

            modelBuilder.Entity("Data.Models.Reportes", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneradoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservasActivas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservasCanceladas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoReporte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReservas")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReporteId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Data.Models.Reservaciones", b =>
                {
                    b.Property<int>("ReservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoReserva")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservacionId");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("Data.Models.Restaurantes", b =>
                {
                    b.Property<int>("RestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.HasKey("RestauranteId");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("Data.Models.TipoCargo", b =>
                {
                    b.Property<int>("TipoCargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoCargoId");

                    b.ToTable("TiposCargo");
                });

            modelBuilder.Entity("Data.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaCubiculo", b =>
                {
                    b.HasOne("Data.Models.Cubiculos", "Cubiculo")
                        .WithMany()
                        .HasForeignKey("CubiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Estudiantes", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Reservaciones", "Reservacion")
                        .WithMany()
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cubiculo");

                    b.Navigation("Estudiante");

                    b.Navigation("Reservacion");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaLaboratorio", b =>
                {
                    b.HasOne("Data.Models.Estudiantes", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Laboratorios", "Laboratorio")
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Reservaciones", "Reservacion")
                        .WithMany()
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Laboratorio");

                    b.Navigation("Reservacion");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaProyector", b =>
                {
                    b.HasOne("Data.Models.Estudiantes", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Proyectores", "Proyector")
                        .WithMany()
                        .HasForeignKey("ProyectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Reservaciones", "Reservacion")
                        .WithMany()
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Proyector");

                    b.Navigation("Reservacion");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaRestaurante", b =>
                {
                    b.HasOne("Data.Models.Estudiantes", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Reservaciones", "Reservacion")
                        .WithMany()
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Restaurantes", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Reservacion");

                    b.Navigation("Restaurante");
                });
#pragma warning restore 612, 618
        }
    }
}
