// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URESERVE_Api.DAL;

#nullable disable

namespace URESERVE_Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250729174425_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Data.Models.Cubiculos", b =>
                {
                    b.Property<int>("CubiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CubiculoId");

                    b.ToTable("Cubiculos");

                    b.HasData(
                        new
                        {
                            CubiculoId = 1,
                            Disponible = true,
                            Nombre = "Cubículo 1"
                        },
                        new
                        {
                            CubiculoId = 2,
                            Disponible = true,
                            Nombre = "Cubículo 2"
                        },
                        new
                        {
                            CubiculoId = 3,
                            Disponible = true,
                            Nombre = "Cubículo 3"
                        },
                        new
                        {
                            CubiculoId = 4,
                            Disponible = true,
                            Nombre = "Cubículo 4"
                        },
                        new
                        {
                            CubiculoId = 5,
                            Disponible = true,
                            Nombre = "Cubículo 5"
                        },
                        new
                        {
                            CubiculoId = 6,
                            Disponible = true,
                            Nombre = "Cubículo 6"
                        },
                        new
                        {
                            CubiculoId = 7,
                            Disponible = true,
                            Nombre = "Cubículo 7"
                        },
                        new
                        {
                            CubiculoId = 8,
                            Disponible = false,
                            Nombre = "Cubículo 8"
                        },
                        new
                        {
                            CubiculoId = 9,
                            Disponible = true,
                            Nombre = "Cubículo 9"
                        },
                        new
                        {
                            CubiculoId = 10,
                            Disponible = false,
                            Nombre = "Cubículo 10"
                        });
                });

            modelBuilder.Entity("Data.Models.DetalleReservaCubiculo", b =>
                {
                    b.Property<int>("DetalleReservaCubiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CubiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCubiculo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DetalleReservaCubiculoId");

                    b.HasIndex("CubiculoId");

                    b.ToTable("DetallesReservaCubiculos");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaLaboratorio", b =>
                {
                    b.Property<int>("DetalleReservaLaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdLaboratorio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaboratorioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DetalleReservaLaboratorioId");

                    b.HasIndex("LaboratorioId");

                    b.ToTable("DetallesReservaLaboratorios");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaProyector", b =>
                {
                    b.Property<int>("DetalleReservaProyectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProyector")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProyectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleReservaProyectorId");

                    b.HasIndex("ProyectorId");

                    b.ToTable("DetallesReservaProyectores");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaRestaurante", b =>
                {
                    b.Property<int>("DetalleReservaRestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DetalleReservaRestauranteId");

                    b.ToTable("DetallesReservaRestaurantes");
                });

            modelBuilder.Entity("Data.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Data.Models.Laboratorios", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LaboratorioId");

                    b.ToTable("Laboratorios");

                    b.HasData(
                        new
                        {
                            LaboratorioId = 1,
                            Disponible = true,
                            Nombre = "Laboratorio A"
                        },
                        new
                        {
                            LaboratorioId = 2,
                            Disponible = true,
                            Nombre = "Laboratorio B"
                        },
                        new
                        {
                            LaboratorioId = 3,
                            Disponible = true,
                            Nombre = "Laboratorio C"
                        },
                        new
                        {
                            LaboratorioId = 4,
                            Disponible = true,
                            Nombre = "Laboratorio D"
                        },
                        new
                        {
                            LaboratorioId = 5,
                            Disponible = true,
                            Nombre = "Laboratorio E"
                        });
                });

            modelBuilder.Entity("Data.Models.Proyectores", b =>
                {
                    b.Property<int>("ProyectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conectividad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProyectorId");

                    b.ToTable("Proyectores");

                    b.HasData(
                        new
                        {
                            ProyectorId = 1,
                            Cantidad = 5,
                            Conectividad = "HDMI, VGA",
                            Nombre = "Proyector Epson EB-X41"
                        },
                        new
                        {
                            ProyectorId = 2,
                            Cantidad = 3,
                            Conectividad = "HDMI, USB, Wireless",
                            Nombre = "Proyector BenQ MW632"
                        },
                        new
                        {
                            ProyectorId = 3,
                            Cantidad = 2,
                            Conectividad = "HDMI, VGA, LAN",
                            Nombre = "Proyector Sony VPL-DX120"
                        },
                        new
                        {
                            ProyectorId = 4,
                            Cantidad = 4,
                            Conectividad = "HDMI, VGA, USB",
                            Nombre = "Proyector Optoma X341"
                        });
                });

            modelBuilder.Entity("Data.Models.Reportes", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneradoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservasActivas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservasCanceladas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoReporte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReservas")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReporteId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Data.Models.Reservaciones", b =>
                {
                    b.Property<int>("ReservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoReserva")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservacionId");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("Data.Models.Restaurantes", b =>
                {
                    b.Property<int>("RestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RestauranteId");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("Data.Models.TarjetaCredito", b =>
                {
                    b.Property<int>("TarjetaCreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("codigoSeguridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("fechaVencimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreTitular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroTarjeta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TarjetaCreditoId");

                    b.ToTable("TarjetaCredito");
                });

            modelBuilder.Entity("Data.Models.TipoCargo", b =>
                {
                    b.Property<int>("TipoCargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoCargoId");

                    b.ToTable("TiposCargo");
                });

            modelBuilder.Entity("Data.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaCubiculo", b =>
                {
                    b.HasOne("Data.Models.Cubiculos", "Cubiculo")
                        .WithMany()
                        .HasForeignKey("CubiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cubiculo");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaLaboratorio", b =>
                {
                    b.HasOne("Data.Models.Laboratorios", "Laboratorio")
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("Data.Models.DetalleReservaProyector", b =>
                {
                    b.HasOne("Data.Models.Proyectores", "Proyector")
                        .WithMany()
                        .HasForeignKey("ProyectorId");

                    b.Navigation("Proyector");
                });

            modelBuilder.Entity("Data.Models.Usuarios", b =>
                {
                    b.HasOne("Data.Models.Estudiantes", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId");

                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
